services:
  devcontainer:
    image: ghcr.io/xcape-inc/fido2luks/devcontainer
    build: 
      dockerfile: ".devcontainer/Dockerfile"
      context: ..
    volumes:
      - ..:/workspace:delegated
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker-host.sock
      - ${HOME}/.ssh:/home/vscode/.ssh
    environment:
      - "LOCAL_WORKSPACE_FOLDER=/workspace"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    init: true
